services:
  - type: web
    name: inventory-demand-prediction
    runtime: python
    rootDir: inventory-demand-prediction
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
